Hashtags= [{'Hashtag': 'Rooney', 'Keywords': ['rooney', 'wayne rooney', 'wayne']},
 {'Hashtag': 'Mourinho', 'Keywords': ['jose', 'mourinho']},
 {'Hashtag': 'DeGea', 'Keywords': ['david', 'de gea']},
 {'Hashtag': 'Jones', 'Keywords': ['phil', 'jones']},
 {'Hashtag': 'Smalling', 'Keywords': ['smalling', 'chris']},
 {'Hashtag': 'Lindelof', 'Keywords': ['lindelof', 'victor']},
 {'Hashtag': 'Bailly', 'Keywords': ['eric', 'bailly']},
 {'Hashtag': 'Jones', 'Keywords': ['jones', 'phil']},
 {'Hashtag': 'Rojo', 'Keywords': ['rojo', 'marcos']},
 {'Hashtag': 'Pogba', 'Keywords': ['pogboom', 'pogba']},
 {'Hashtag': 'Sanchez', 'Keywords': ['sanchez', 'alexis', 'humber', 'atom']},
 {'Hashtag': 'Mata', 'Keywords': ['juan', 'hugs', 'mata']},
 {'Hashtag': 'Lukaku', 'Keywords': ['romelu', 'lukaku']},
 {'Hashtag': 'Ibrahimovic',
  'Keywords': ['zlat10', 'ibra', 'ibrahimovic', 'zlatan', 'zlat']},
 {'Hashtag': 'Martial', 'Keywords': ['martial', 'anthony', 'tony']},
 {'Hashtag': 'Lingard', 'Keywords': ['jesse', 'lingard']},
 {'Hashtag': 'Pereira', 'Keywords': ['andreas', 'pereira']},
 {'Hashtag': 'Carrick', 'Keywords': ['michael', 'carrick']},
 {'Hashtag': 'Blind', 'Keywords': ['blind', 'daley']},
 {'Hashtag': 'Young', 'Keywords': ['young', 'ashley']},
 {'Hashtag': 'Rashford', 'Keywords': ['rashford', 'marcus']},
 {'Hashtag': 'Romero', 'Keywords': ['romero', 'sergio']},
 {'Hashtag': 'Herrera', 'Keywords': ['herrera', 'ander']},
 {'Hashtag': 'Shaw', 'Keywords': ['luke', 'shaw']},
 {'Hashtag': 'FosuMensah', 'Keywords': ['fosumensah', 'timothy', 'fosu']},
 {'Hashtag': 'Fellaini', 'Keywords': ['marouane', 'fellaini']},
 {'Hashtag': 'Matic', 'Keywords': ['matic', 'nemanja']},
 {'Hashtag': 'Darmian', 'Keywords': ['darmian', 'matteo']},
 {'Hashtag': 'Tuanzebe', 'Keywords': ['axel', 'tuanzebe']},
 {'Hashtag': 'McTominay', 'Keywords': ['scott', 'mctominay']},
 {'Hashtag': 'OldTrafford',
  'Keywords': ['old trafford', ' ot ', 'oldtrafford']},
 {'Hashtag': 'SirAlex', 'Keywords': ['siralex', 'ferguson']},
 {'Hashtag': 'SirAlexFerguson', 'Keywords': ['sir alex', 'siralexferguson']},
 {'Hashtag': 'PremierLeague', 'Keywords': ['premier league', 'premierleague']},
 {'Hashtag': 'ChampionsLeague',
  'Keywords': ['championsleague', ' cl ', 'champions league']},
 {'Hashtag': 'FACup', 'Keywords': ['fa cup', 'facup']}]
